---
kind: pipeline
type: kubernetes
name: default
steps:
  # Generate docker image
  - name: docker-release
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: nox404/dynhost-ovh
      auto_tag: yes
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  # Alerting
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: mattermost_hook
    when:
      status:
      - failure
      - success
---
kind: signature
hmac: 05bea3393f3f25bae713aeac5479dbc344bb756ac7930241ba5e66544f909568

...
