{{- if not .Values.dynhost.externalSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynhost-ovh.fullname" . }}
  labels:
    {{- include "dynhost-ovh.labels" . | nindent 4 }}
type: Opaque
data:
  HOST: {{ .Values.dynhost.host | required "dynhost.host is required" | b64enc }}
  LOGIN: {{ .Values.dynhost.login | required "dynhost.login is required" | b64enc }}
  PASSWORD: {{ .Values.dynhost.password | required "dynhost.password is required" | b64enc }}
{{- end }}
